// Cell types: 0 = empty, 1 = crater, 2 = crystal, 3 = rover start
// Direction: 0 = up, 1 = right, 2 = down, 3 = left

export const LEVELS = [
  {
    id: 1,
    title: "Operação Marte - Nível 1",
    subtitle: "Aprenda a avançar",
    gridSize: { rows: 5, cols: 5 },
    roverStart: { row: 4, col: 0, direction: 0 },
    grid: [
      [0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0],
      [0, 0, 1, 0, 0],
      [0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0],
    ],
    crystals: [{ row: 0, col: 0 }],
    maxCommands: 6,
    hint: "Use 'Avançar' para mover o rover para cima!",
    availableCommands: ["forward", "right", "left"],
  },
  {
    id: 2,
    title: "Operação Marte - Nível 2",
    subtitle: "Desviando de crateras",
    gridSize: { rows: 6, cols: 6 },
    roverStart: { row: 5, col: 0, direction: 0 },
    grid: [
      [0, 0, 0, 0, 0, 0],
      [0, 1, 0, 0, 1, 0],
      [0, 0, 0, 1, 0, 0],
      [0, 1, 0, 0, 0, 0],
      [0, 0, 0, 1, 0, 0],
      [0, 0, 0, 0, 0, 0],
    ],
    crystals: [{ row: 0, col: 5 }],
    maxCommands: 12,
    hint: "Gire o rover para desviar das crateras!",
    availableCommands: ["forward", "right", "left"],
  },
  {
    id: 3,
    title: "Operação Marte - Nível 3",
    subtitle: "Use repetições!",
    gridSize: { rows: 7, cols: 7 },
    roverStart: { row: 6, col: 0, direction: 1 },
    grid: [
      [0, 0, 0, 0, 0, 0, 0],
      [0, 0, 1, 0, 1, 0, 0],
      [0, 0, 0, 0, 0, 0, 0],
      [0, 1, 0, 1, 0, 1, 0],
      [0, 0, 0, 0, 0, 0, 0],
      [0, 0, 1, 0, 1, 0, 0],
      [0, 0, 0, 0, 0, 0, 0],
    ],
    crystals: [{ row: 0, col: 6 }],
    maxCommands: 10,
    hint: "Use 'Repetir' para economizar comandos!",
    availableCommands: ["forward", "right", "left", "repeat"],
  },
  {
    id: 4,
    title: "Operação Marte - Nível 4",
    subtitle: "Múltiplos cristais",
    gridSize: { rows: 7, cols: 7 },
    roverStart: { row: 6, col: 3, direction: 0 },
    grid: [
      [0, 0, 0, 0, 0, 0, 0],
      [0, 1, 0, 0, 0, 1, 0],
      [0, 0, 0, 1, 0, 0, 0],
      [1, 0, 0, 0, 0, 0, 1],
      [0, 0, 1, 0, 1, 0, 0],
      [0, 0, 0, 0, 0, 0, 0],
      [0, 0, 0, 0, 0, 0, 0],
    ],
    crystals: [
      { row: 0, col: 0 },
      { row: 0, col: 6 },
      { row: 3, col: 3 },
    ],
    maxCommands: 20,
    hint: "Colete todos os cristais para vencer!",
    availableCommands: ["forward", "right", "left", "repeat"],
  },
  {
    id: 5,
    title: "Operação Marte - Nível 5",
    subtitle: "Desafio final!",
    gridSize: { rows: 8, cols: 8 },
    roverStart: { row: 7, col: 0, direction: 0 },
    grid: [
      [0, 0, 0, 1, 0, 0, 0, 0],
      [0, 1, 0, 0, 0, 1, 0, 0],
      [0, 0, 0, 1, 0, 0, 0, 1],
      [1, 0, 0, 0, 0, 1, 0, 0],
      [0, 0, 1, 0, 0, 0, 0, 0],
      [0, 0, 0, 0, 1, 0, 1, 0],
      [0, 1, 0, 0, 0, 0, 0, 0],
      [0, 0, 0, 1, 0, 0, 1, 0],
    ],
    crystals: [
      { row: 0, col: 7 },
      { row: 4, col: 4 },
    ],
    maxCommands: 25,
    hint: "Planeje bem sua rota pelo labirinto!",
    availableCommands: ["forward", "right", "left", "repeat"],
  },
];